"""empty message

Revision ID: 19a8d51609b1
Revises: b39ddc70485e
Create Date: 2023-09-23 22:40:10.090906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a8d51609b1'
down_revision = 'b39ddc70485e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_second_post', schema=None) as batch_op:
        batch_op.alter_column('amenities',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('listing_description',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('total_floor',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('total_room',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('room_area',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('room_name',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('room_price',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('discount',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('additional_info',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_second_post', schema=None) as batch_op:
        batch_op.alter_column('additional_info',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('discount',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('room_price',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('room_name',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('room_area',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('total_room',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('total_floor',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('listing_description',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('amenities',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)

    # ### end Alembic commands ###
