"""listing migration

Revision ID: 346d29f83878
Revises: 9a33f7813342
Create Date: 2023-09-11 15:25:34.742131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346d29f83878'
down_revision = '9a33f7813342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('thumbnail_image', sa.String(length=140), nullable=False),
    sa.Column('gallery_image', sa.String(length=140), nullable=False),
    sa.Column('room_thumbnail_image', sa.String(length=140), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_post', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_image')
        batch_op.drop_column('gallery_image')
        batch_op.drop_column('room_thumbnail_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_thumbnail_image', sa.VARCHAR(length=140), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('gallery_image', sa.VARCHAR(length=140), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('thumbnail_image', sa.VARCHAR(length=140), autoincrement=False, nullable=False))

    op.drop_table('listing_pictures')
    # ### end Alembic commands ###
