"""rebase

Revision ID: 41824a150a42
Revises: 0ed6d4c82b66
Create Date: 2023-11-04 16:38:28.371654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41824a150a42'
down_revision = '0ed6d4c82b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('listing_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('thumbnail_image', sa.String(length=1024), nullable=True),
    sa.Column('gallery_images', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('listing_type', sa.String(length=140), nullable=True),
    sa.Column('listing_name', sa.String(length=140), nullable=True),
    sa.Column('amount_land', sa.String(length=140), nullable=True),
    sa.Column('short_description', sa.String(length=140), nullable=True),
    sa.Column('country', sa.String(length=140), nullable=True),
    sa.Column('state', sa.String(length=140), nullable=True),
    sa.Column('city', sa.String(length=140), nullable=True),
    sa.Column('postal_code', sa.String(length=140), nullable=True),
    sa.Column('street', sa.String(length=140), nullable=True),
    sa.Column('longitude', sa.String(length=140), nullable=True),
    sa.Column('latitude', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing_second_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('amenities', sa.String(length=140), nullable=True),
    sa.Column('listing_description', sa.String(length=140), nullable=True),
    sa.Column('total_floor', sa.String(length=140), nullable=True),
    sa.Column('total_room', sa.String(length=140), nullable=True),
    sa.Column('room_area', sa.String(length=140), nullable=True),
    sa.Column('room_name', sa.String(length=140), nullable=True),
    sa.Column('room_price', sa.String(length=140), nullable=True),
    sa.Column('discount', sa.String(length=140), nullable=True),
    sa.Column('additional_info', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solar_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stripe_customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stripe_customer')
    op.drop_table('solar_post')
    op.drop_table('listing_second_post')
    op.drop_table('listing_post')
    op.drop_table('listing_pictures')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
