"""listings

Revision ID: 5aaabc9f4a8e
Revises: f3fde6ba9507
Create Date: 2023-10-04 21:39:49.980266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aaabc9f4a8e'
down_revision = 'f3fde6ba9507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_pictures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'listing_post', ['listing_id'], ['id'])

    with op.batch_alter_table('listing_second_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'listing_post', ['listing_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_second_post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('listing_id')

    with op.batch_alter_table('listing_pictures', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('listing_id')

    # ### end Alembic commands ###
