"""listing without validators

Revision ID: 7c06afa5fe9e
Revises: 4f5d3c230e39
Create Date: 2023-09-13 11:25:04.386577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c06afa5fe9e'
down_revision = '4f5d3c230e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_post', schema=None) as batch_op:
        batch_op.alter_column('listing_type',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('listing_name',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('amount_land',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('short_description',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('street',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_post', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('street',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('postal_code',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('short_description',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('amount_land',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('listing_name',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('listing_type',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)

    # ### end Alembic commands ###
