"""second migration with listing

Revision ID: 9a33f7813342
Revises: f4ad1f7b0c63
Create Date: 2023-09-04 23:10:09.540769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a33f7813342'
down_revision = 'f4ad1f7b0c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('listing_type', sa.String(length=140), nullable=False),
    sa.Column('listing_name', sa.String(length=140), nullable=False),
    sa.Column('amount_land', sa.String(length=140), nullable=False),
    sa.Column('short_description', sa.String(length=140), nullable=False),
    sa.Column('country', sa.String(length=140), nullable=False),
    sa.Column('state', sa.String(length=140), nullable=False),
    sa.Column('city', sa.String(length=140), nullable=False),
    sa.Column('postal_code', sa.String(length=140), nullable=False),
    sa.Column('street', sa.String(length=140), nullable=False),
    sa.Column('longitude', sa.String(length=140), nullable=False),
    sa.Column('latitude', sa.String(length=140), nullable=False),
    sa.Column('thumbnail_image', sa.String(length=140), nullable=False),
    sa.Column('gallery_image', sa.String(length=140), nullable=False),
    sa.Column('amenities', sa.String(length=140), nullable=False),
    sa.Column('listing_description', sa.String(length=140), nullable=False),
    sa.Column('total_floor', sa.String(length=140), nullable=False),
    sa.Column('total_room', sa.String(length=140), nullable=False),
    sa.Column('room_area', sa.String(length=140), nullable=False),
    sa.Column('room_name', sa.String(length=140), nullable=False),
    sa.Column('room_thumbnail_image', sa.String(length=140), nullable=False),
    sa.Column('room_price', sa.String(length=140), nullable=False),
    sa.Column('discount', sa.String(length=140), nullable=False),
    sa.Column('additional_info', sa.String(length=140), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listing_post')
    # ### end Alembic commands ###
