"""amount_land to int

Revision ID: b39ddc70485e
Revises: 7c06afa5fe9e
Create Date: 2023-09-15 22:50:01.218141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b39ddc70485e'
down_revision = '7c06afa5fe9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_post', schema=None) as batch_op:
        batch_op.alter_column('amount_land',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_post', schema=None) as batch_op:
        batch_op.alter_column('amount_land',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)

    # ### end Alembic commands ###
