"""eliminate listing_id

Revision ID: e612b91aa4a6
Revises: bb12a3c84fce
Create Date: 2023-10-09 14:24:18.858512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e612b91aa4a6'
down_revision = 'bb12a3c84fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_pictures', schema=None) as batch_op:
        batch_op.drop_constraint('listing_pictures_listing_id_fkey', type_='foreignkey')
        batch_op.drop_column('listing_id')

    with op.batch_alter_table('listing_second_post', schema=None) as batch_op:
        batch_op.drop_constraint('listing_second_post_listing_id_fkey', type_='foreignkey')
        batch_op.drop_column('listing_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_second_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('listing_second_post_listing_id_fkey', 'listing_post', ['listing_id'], ['id'])

    with op.batch_alter_table('listing_pictures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('listing_pictures_listing_id_fkey', 'listing_post', ['listing_id'], ['id'])

    # ### end Alembic commands ###
