"""pictures

Revision ID: f3fde6ba9507
Revises: 19a8d51609b1
Create Date: 2023-09-26 12:20:35.188755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3fde6ba9507'
down_revision = '19a8d51609b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_pictures', schema=None) as batch_op:
        batch_op.alter_column('thumbnail_image',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('gallery_image',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.drop_column('room_thumbnail_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_pictures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_thumbnail_image', sa.VARCHAR(length=140), autoincrement=False, nullable=False))
        batch_op.alter_column('gallery_image',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('thumbnail_image',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)

    # ### end Alembic commands ###
